apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: dev1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: hoouinkyouma/app:1.0
          resources:
            limits:
              cpu: "250m"
              memory: "128Mi"
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              value: order_user
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: order_db
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: dev1
spec:
  selector:
    app: order
  ports:
  - port: 5002
    targetPort: 8000
